- name: Retrieve access token via SSO script
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Run Python script to get token
      script: auth.py
      register: token_result

    - name: Output the token
      debug:
        msg: "Token: {{ token_result.stdout }}"
